version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-oms
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nom_de_ta_bd
      POSTGRES_USER: proxiad
      POSTGRES_PASSWORD: proxiad
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
